# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -

before_install: gem install xcpretty --no-ri --no-rdoc

script:
- (xcodebuild test -workspace Inapp.xcworkspace -scheme Inapp -sdk iphonesimulator && xcodebuild  test -workspace Inapp.xcworkspace -scheme InappExample -sdk iphonesimulator) | xcpretty -c

notifications:
  email:
    - index.e@klarna.com
