# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -

script:
- xcodebuild test -workspace Inapp.xcworkspace -scheme Inapp -sdk iphonesimulator | xcpretty -c
- xcodebuild test -workspace Inapp.xcworkspace -scheme InappExample -sdk iphonesimulator | xcpretty -c

notifications:
  email:
    - index.e@klarna.com
