# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

script:
# Change the example app's API key to circumvent Ringcaptcha
- sed -i "" 's/test_d8324b98-97ce-4974-88de-eaab2fdf4f14/test_6666666-6666-6666-6666-666666666666/g' **/*.m

- set -o pipefail && xcodebuild test -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemand -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' | xcpretty -c
- set -o pipefail && xcodebuild -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemandExample -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' | xcpretty -c

notifications:
  email:
    - index.e@klarna.com
