language: objective-c
osx_image: xcode7.3

addons:
  sauce_connect: true

install:
- pod install
- (cd integration-tests && bundle install)

script:
# Build & run tests
- set -o pipefail && xcodebuild test -derivedDataPath build -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemand -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' | xcpretty -c
- set -o pipefail && xcodebuild test -derivedDataPath build -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemandExample -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -c

# Change the example app's API key to circumvent Ringcaptcha
- find Example -name "*.m" -print0 | xargs -0 sed -i "" 's#test_d8324b98-97ce-4974-88de-eaab2fdf4f14#test_6666666-6666-6666-6666-666666666666#g'
# Direct the app to the sample backend on Heroku
- find Example -name "*.m" -print0 | xargs -0 sed -i "" 's#http://localhost:9292/pay#https://sample-ondemand-backend.herokuapp.com/pay#g'

# TODO - https://jira.int.klarna.net/jira/browse/IACO-915 - fix integration tests:
# Zip the app and send it to SauceLabs
# - zip -r KODSampleApp.zip build/Build/Products/Debug-iphonesimulator/KlarnaOnDemandExample.app
# - "curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY -X POST \"http://saucelabs.com/rest/v1/storage/$SAUCE_USERNAME/KODSampleApp.zip?overwrite=true\" -H \"Content-Type: application/octet-stream\" --data-binary @KODSampleApp.zip"
# Run integration tests through SauceLabs
# - (cd integration-tests && APP_LOCATION=sauce-storage:KODSampleApp.zip PLATFORM=ios bundle exec cucumber)

notifications:
  email:
  - on.demand.e@klarna.com

env:
  global:
  - secure: fqi0W7DMUXDRJNI7zc9kao2fxTGzNPVGWcnBJkTMfabb05iT7eDOooZHoUas/Ctogklt+lkEpr2V0GcgliJ4sVPWJ9L8wPy3BcrVHZq7Of3bAoB9d30ISH4qhMVITdIFHnXS8V4AHOvig9g83PcN4Kor+KQKHYyjiIu8KYrxvLU=
  - secure: EimNhOU3jiHJtpSLfEPb/Ga7L0qw/3Eobnx6n+2pIB1oEj17bxH65MNwg2A1+lCUuLEUXUzGiFLwTFMU870AGXpeWs+APPaEtKQY6IJgiKh3S+xk0rbHUh3i3xXULq15ClTEIQVb6UVkdPHy05Nnb/1IZwpJung0eFDQmhOJOJ8=
