# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -

script:
- xctool test -workspace Inapp.xcworkspace -scheme Inapp -sdk iphonesimulator && xctool test -workspace Inapp.xcworkspace -scheme InappExample -sdk iphonesimulator

notifications:
  email:
    - index.e@klarna.com
