# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

script:
- xctool -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemand -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' test
- xctool -workspace KlarnaOnDemand.xcworkspace -scheme KlarnaOnDemandExample -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.1' build

notifications:
  email:
    - index.e@klarna.com
