# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# before_install: cd Example && pod install && cd -

script:
- xctool -workspace Inapp.xcworkspace -scheme Inapp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool -workspace Inapp.xcworkspace -scheme InappExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    - index.e@klarna.com
